ARG GO_BUILDER=registry.ci.openshift.org/openshift/release:rhel-9-release-golang-1.26-openshift-5.0@sha256:2794558986b3daeb5e4dc57fb9fd5f7b0812599192d4ff0a1a8247791a38ca60
ARG GO_RUNTIME=registry.access.redhat.com/ubi9/ubi-minimal@sha256:7fbeae18dc9476399f565e68255f602a3374ea8614ba3d14843565131a13ff93

# Reference to the func-util image, baked into the func binary at build time
# so it knows which image to use for in-cluster helper tasks (socat, tar,
# deploy/scaffold/s2i pipeline steps).
ARG FUNC_UTILS_IMG=quay.io/redhat-user-workloads/ocp-serverless-tenant/functions-utils@sha256:076db2ad7ce7e7eeff760419dd6bc2c80a96d4228ac93734646fd84d1795d059

FROM $GO_BUILDER as builder

ARG FUNC_UTILS_IMG

WORKDIR /workspace
COPY . .

ENV CGO_ENABLED=1
ENV GOEXPERIMENT=strictfipsruntime
ENV GOFLAGS=''

RUN if [ -f /cachi2/cachi2.env ]; then source /cachi2/cachi2.env; fi && \
	go build -tags strictfipsruntime,exclude_graphdriver_btrfs \
	-ldflags "-X knative.dev/func/pkg/k8s.SocatImage=$FUNC_UTILS_IMG \
	-X knative.dev/func/pkg/k8s.TarImage=$FUNC_UTILS_IMG \
	-X knative.dev/func/pkg/pipelines/tekton.FuncUtilImage=$FUNC_UTILS_IMG" \
	-o /usr/bin/func ./cmd/func

FROM $GO_RUNTIME

COPY --from=builder /usr/bin/func /usr/bin/func
COPY LICENSE /licenses/

USER 65532

LABEL name="openshift-serverless-tech-preview/functions-func-rhel9" \
      com.redhat.component="openshift-serverless-functions-func-container" \
      version="2.0" \
      release="1" \
      summary="OpenShift Serverless Functions func container" \
      description="Provides the func tool for OpenShift Serverless Functions." \
      io.k8s.display-name="OpenShift Serverless Functions Func" \
      io.k8s.description="Provides the func tool for OpenShift Serverless Functions." \
      io.openshift.tags="openshift,serverless,functions,func" \
      maintainer="serverless-support@redhat.com"

ENTRYPOINT ["/usr/bin/func"]
