ARG GO_BUILDER=registry.ci.openshift.org/openshift/release:rhel-9-release-golang-1.26-openshift-5.0
ARG GO_RUNTIME=registry.access.redhat.com/ubi9/ubi-minimal

FROM $GO_BUILDER as builder

WORKDIR /workspace
COPY . .

ENV CGO_ENABLED=1
ENV GOEXPERIMENT=strictfipsruntime
ENV GOFLAGS=''

RUN if [ -f /cachi2/cachi2.env ]; then source /cachi2/cachi2.env; fi && \
	go build -tags strictfipsruntime,exclude_graphdriver_btrfs -o /usr/bin/main ./cmd/func-util

FROM $GO_RUNTIME

RUN microdnf install -y socat tar

COPY --from=builder /usr/bin/main /usr/bin/func-util
COPY LICENSE /licenses/

RUN ln -s /usr/bin/func-util /usr/local/bin/deploy && \
	ln -s /usr/bin/func-util /usr/local/bin/scaffold && \
	ln -s /usr/bin/func-util /usr/local/bin/s2i && \
	ln -s /usr/bin/func-util /usr/local/bin/s2i-generate

USER 65532

LABEL name="openshift-serverless-tech-preview/functions-utils-rhel9" \
      com.redhat.component="openshift-serverless-functions-utils-container" \
      version="2.0" \
      release="1" \
      summary="OpenShift Serverless Functions utility container" \
      description="Provides utility tools (deploy, scaffold, s2i) for OpenShift Serverless Functions." \
      io.k8s.display-name="OpenShift Serverless Functions Utils" \
      io.k8s.description="Provides utility tools (deploy, scaffold, s2i) for OpenShift Serverless Functions." \
      io.openshift.tags="openshift,serverless,functions,utils" \
      maintainer="serverless-support@redhat.com"

ENTRYPOINT ["/usr/bin/bash"]
