ARG GO_BUILDER=registry.ci.openshift.org/openshift/release:rhel-9-release-golang-1.26-openshift-5.0@sha256:c8610d237f5ac06e482d5ae635e2bd97c85a4476bfe3a46c236ed38fed2eb060
ARG GO_RUNTIME=registry.access.redhat.com/ubi9/ubi-minimal@sha256:7b8e25a1b56ca4d00219198f3b5b51a3e1693a5c4f5369c5e190d7d6cb3f980e

# Reference to the func-util image, baked into the func binary at build time
# so it knows which image to use for in-cluster helper tasks (socat, tar,
# deploy/scaffold/s2i pipeline steps).
ARG FUNC_UTILS_IMG=registry.redhat.io/openshift-serverless-tech-preview/functions-utils-rhel9@sha256:64193f6f974377272df77142d900be472df72dd866e101676f917155436c2503

FROM $GO_BUILDER as builder

ARG FUNC_UTILS_IMG

WORKDIR /workspace
COPY . .

ENV CGO_ENABLED=1
ENV GOEXPERIMENT=strictfipsruntime
ENV GOFLAGS=''

RUN if [ -f /cachi2/cachi2.env ]; then source /cachi2/cachi2.env; fi && \
	go build -tags strictfipsruntime,exclude_graphdriver_btrfs \
	-ldflags "-X knative.dev/func/pkg/k8s.SocatImage=$FUNC_UTILS_IMG \
	-X knative.dev/func/pkg/k8s.TarImage=$FUNC_UTILS_IMG \
	-X knative.dev/func/pkg/pipelines/tekton.FuncUtilImage=$FUNC_UTILS_IMG" \
	-o /usr/bin/func ./cmd/func

FROM $GO_RUNTIME

COPY --from=builder /usr/bin/func /usr/bin/func
COPY LICENSE /licenses/

USER 65532

LABEL name="openshift-serverless-tech-preview/functions-func-rhel9" \
      com.redhat.component="openshift-serverless-functions-func-container" \
      version="2.0" \
      release="1" \
      summary="OpenShift Serverless Functions func container" \
      description="Provides the func tool for OpenShift Serverless Functions." \
      io.k8s.display-name="OpenShift Serverless Functions Func" \
      io.k8s.description="Provides the func tool for OpenShift Serverless Functions." \
      io.openshift.tags="openshift,serverless,functions,func" \
      maintainer="serverless-support@redhat.com" \
      cpe="cpe:/a:redhat:openshift_serverless:2.0::el9"

ENTRYPOINT ["/usr/bin/func"]
