ARG GO_BUILDER=registry.ci.openshift.org/openshift/release:rhel-9-release-golang-1.26-openshift-5.0
ARG GO_RUNTIME=registry.access.redhat.com/ubi9/ubi-minimal

# Reference to the func-util image, baked into the func binary at build time
# so it knows which image to use for in-cluster helper tasks (socat, tar,
# deploy/scaffold/s2i pipeline steps).
ARG FUNC_UTILS_IMG=quay.io/redhat-user-workloads/ocp-serverless-tenant/functions-utils@sha256:6e6587fdcaee4d344b4daa3b4d571bbc111253f1e8ff7e4594822a99754fa2a2

FROM $GO_BUILDER as builder

ARG FUNC_UTILS_IMG

WORKDIR /workspace
COPY . .

ENV CGO_ENABLED=1
ENV GOEXPERIMENT=strictfipsruntime
ENV GOFLAGS=''

RUN go build -tags strictfipsruntime,exclude_graphdriver_btrfs \
	-ldflags "-X knative.dev/func/pkg/k8s.SocatImage=$FUNC_UTILS_IMG \
	-X knative.dev/func/pkg/k8s.TarImage=$FUNC_UTILS_IMG \
	-X knative.dev/func/pkg/pipelines/tekton.FuncUtilImage=$FUNC_UTILS_IMG" \
	-o /usr/bin/func ./cmd/func

FROM $GO_RUNTIME

COPY --from=builder /usr/bin/func /usr/bin/func
COPY LICENSE /licenses/

USER 65532

ENTRYPOINT ["/usr/bin/func"]
